### ISSUE TITLE
Redirect URL & First Reply Url

### ISSUE THREAD

**Issue by yashijoe** [chemaaa/homepluscontrol#3]
Hello chemaaa, first thank you for your integration!
I've no idea what to put in the Redirect URL & First Reply Url fields. Both of them are mandatory
Can you help me?
Thanks a lot

**Comment by chemaaa** [comment]
Hi @yashijoe ,

Are you referring to the "New Application" form in the Legrand Developer website? If so, here you have some more information about how that should be filled in: https://developer.legrand.com/tutorials/create-an-application/

Basically, you have to fill in a "Url" which is just an informative URL about the application. If this is for Home Assistant integration, I don't think it is of much relevance.

The more important URL is the "First Reply Url"... that one is the Redirect URI for the OAuth2 authentication flow. This should be filled in with the URL of your application. Again, if this is for Home Assistant integration, you should enter the URL that you use to access your HA instance, for example: https://my-ha-ip-address:8123

Let me know if this clarifies.

Regards.

**Comment by yashijoe** [comment]
Thank you chemaaa, so my configuration should be fine
As I'm not getting any devices discovered, I guess the issue is on the 2 subnets I have. One for IOT and one for PCs and home assistant raspberry.
I'll try to move the legrand gateway on the main subnet
Thanks
